### ISSUE TITLE
best_answer取得時にinformative_countがないので見出し取得に失敗する

### ISSUE THREAD

**Issue by shibayaman** [akisu1016/what-is-grass-backend#41]
## 問題
見出し取得全般ができませんでした。

## 再現方法
`http://localhost:8080/api/question?language_id=1`
にリクエストを送ると500が返りました。

pythonのサーバーのログ↓
```
172.23.0.1 - - [07/Sep/2021 11:11:46] "GET /api/question?language_id=1 HTTP/1.1" 500 -
whatisgrass-api      | Traceback (most recent call last):
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
whatisgrass-api      |     return self.wsgi_app(environ, start_response)
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
whatisgrass-api      |     response = self.handle_exception(e)
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
whatisgrass-api      |     return cors_after_request(app.make_response(f(*args, **kwargs)))
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
whatisgrass-api      |     response = self.full_dispatch_request()
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
whatisgrass-api      |     rv = self.handle_user_exception(e)
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
whatisgrass-api      |     return cors_after_request(app.make_response(f(*args, **kwargs)))
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
whatisgrass-api      |     rv = self.dispatch_request()
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
whatisgrass-api      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
whatisgrass-api      |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 125, in decorator
whatisgrass-api      |     return current_app.ensure_sync(fn)(*args, **kwargs)
whatisgrass-api      |   File "/app/api/views/question.py", line 74, in getIndexList
whatisgrass-api      |     indices = Index.getIndexList(request_dict)
whatisgrass-api      |   File "/app/api/models/index.py", line 55, in getIndexList
whatisgrass-api      |     best_answer = Index.get_best_answer()
whatisgrass-api      |   File "/app/api/models/index.py", line 384, in get_best_answer
whatisgrass-api      |     Answer.index_id, func.max(Answer.informative_count).label("max_count")
```

見出し取得系の他のAPIも同様に落ちました。
`app/api/models/index.py`のget_best_answerの[この辺](https://github.com/akisu1016/what-is-grass-backend/blob/develop/app/api/models/index.py#L384)が怪しいと思います。Answerの役に立つカウントを別表に移したのに、Answer表から直でinformative_countを取ろうとしてるのが問題な気がするのですがパイチョンが読めません。

**Comment by shibayaman** [comment]
#42
解決済み
